### ISSUE TITLE
`getUserByAccount` Error Using Hasura Example

### ISSUE THREAD

**Issue by lewisdawson** [AmruthPillai/next-auth-hasura-adapter#3]
I am seeing the following error when I try the example provided [here](https://hasura.io/learn/graphql/hasura-authentication/integrations/nextjs-auth/). I've created the table structure defined in the article. I was trying out the Github OAuth integration. Could be wrong, but it seems like the `getUserByAccount` function is trying to filter on the `accounts` field in the `Users` model/table, but that field doesn't exist in the schema. Thoughts?

```
API handler should not return a value, received object.
[next-auth][error][adapter_error_getUserByAccount] 
https://next-auth.js.org/errors#adapter_error_getuserbyaccount field 'accounts' not found in type: 'users_bool_exp': {"response":{"errors":[{"message":"field 'accounts' not found in type: 'users_bool_exp'","extensions":{"path":"$.selectionSet.users.args.where.accounts","code":"validation-failed"}}],"status":200,"headers":{}},"request":{"query":"query GetUsers($where: users_bool_exp!) {\n  users(where: $where) {\n    ...User\n  }\n}\n\nfragment User on users {\n  __typename\n  id\n  name\n  email\n  image\n  emailVerified\n}","variables":{"where":{"accounts":{"provider":{"_eq":"github"},"providerAccountId":{"_eq":"5010504"}}}}}} {
  message: `field 'accounts' not found in type: 'users_bool_exp': {"response":{"errors":[{"message":"field 'accounts' not found in type: 'users_bool_exp'","extensions":{"path":"$.selectionSet.users.args.where.accounts","code":"validation-failed"}}],"status":200,"headers":{}},"request":{"query":"query GetUsers($where: users_bool_exp!) {\\n  users(where: $where) {\\n    ...User\\n  }\\n}\\n\\nfragment User on users {\\n  __typename\\n  id\\n  name\\n  email\\n  image\\n  emailVerified\\n}","variables":{"where":{"accounts":{"provider":{"_eq":"github"},"providerAccountId":{"_eq":"5010504"}}}}}}`,
  stack: `Error: field 'accounts' not found in type: 'users_bool_exp': {"response":{"errors":[{"message":"field 'accounts' not found in type: 'users_bool_exp'","extensions":{"path":"$.selectionSet.users.args.where.accounts","code":"validation-failed"}}],"status":200,"headers":{}},"request":{"query":"query GetUsers($where: users_bool_exp!) {\\n  users(where: $where) {\\n    ...User\\n  }\\n}\\n\\nfragment User on users {\\n  __typename\\n  id\\n  name\\n  email\\n  image\\n  emailVerified\\n}","variables":{"where":{"accounts":{"provider":{"_eq":"github"},"providerAccountId":{"_eq":"5010504"}}}}}}\n` +
    '    at makeRequest (~/next-auth-example/node_modules/graphql-request/build/cjs/index.js:310:15)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async getUserByAccount (~/next-auth-example/node_modules/next-auth-hasura-adapter/dist/index.js:46:25)',
  name: 'Error'
}

```

**Comment by lewisdawson** [comment]
Figured it out. For folks in the future that run into this, you must name the relationship between the `accounts` and `users` types properly. The relationship name needs to be `accounts`. Here's what my relationship looks like after fixing:

<img width="860" alt="image" src="https://github.com/AmruthPillai/next-auth-hasura-adapter/assets/5010504/ae1a6890-4ed2-4eea-a6a8-b32afd1bb315">

**Comment by gyurisc** [comment]
@lewisdawson thank you so much for posting the answer to your issue. You saved me countless hours of banging my head against the wall.

**Comment by lewisdawson** [comment]
@gyurisc Awesome, glad it save you time!
